const express=require('express');
const path=require('path');
const fs=require('fs');
const fsp=fs.promises;
const crypto=require('crypto');
const multer=require('multer');
const {execFile}=require('child_process');
const {promisify}=require('util');
const execFileAsync=promisify(execFile);
const helmet=require('helmet');
const compression=require('compression');
const cookieSession=require('cookie-session');
const {rateLimit}=require('express-rate-limit');

const app=express();
const PORT=Number(process.env.PORT||3000);
const ROOT=__dirname;
const DATA_DIR=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data'));
const UPLOAD_DIR=path.join(DATA_DIR,'uploads');
const TMP_DIR=path.join(DATA_DIR,'tmp');
const DB_PATH=path.join(DATA_DIR,'database.json');
const isProduction=process.env.NODE_ENV==='production';
const baseUrl=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,'');
const SCHEMA_VERSION=4;
let writeQueue=Promise.resolve();
let workerTimer=null;

const id=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const clean=(v,max=4000)=>String(v??'').replace(/[<>]/g,'').trim().slice(0,max);
const bool=(v)=>v===true||v==='true'||v==='on'||v===1;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const phone=(v)=>clean(v,50).replace(/[^+\d\s().-]/g,'');
const email=(v)=>clean(v,180).toLowerCase();
const validEmail=(v)=>/^\S+@\S+\.\S+$/.test(v);
const e164=(v)=>/^\+[1-9]\d{6,14}$/.test(String(v||'').replace(/[\s().-]/g,''));
const safeEquals=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)};

const defaults={
 schemaVersion:SCHEMA_VERSION,
 migrations:{},
 settings:{
  companyName:'Svit&Co',phone:'',email:'',whatsapp:'',viber:'',telegram:'',workingHours:'',serviceArea:'',country:'',
  directButtons:{phone:true,email:true,whatsapp:true,viber:true,telegram:true},
  allowedContactMethods:['phone','whatsapp','viber','telegram','email'],
  hero:{titleUk:'Ремонт квартир під ключ',titleEn:'Complete Apartment Renovation',subtitleUk:'Комплексний ремонт квартир та внутрішнє оздоблення — від узгодження робіт до завершеного інтер’єру.',subtitleEn:'Complete apartment renovation and interior finishing — from planning the work to a finished interior.',image:'/assets/photos/hero-renovation.webp',primaryTextUk:'Отримати консультацію',primaryTextEn:'Get a Consultation',primaryAction:'contact',secondaryTextUk:'Переглянути роботи',secondaryTextEn:'View Our Work',secondaryAction:'projects'},
  seo:{titleUk:'Ремонт квартир під ключ | Svit&Co',titleEn:'Complete Apartment Renovation | Svit&Co',descriptionUk:'Комплексний ремонт квартир та внутрішнє оздоблення.',descriptionEn:'Complete apartment renovation and interior finishing.'},
  brand:{logoUrl:'/assets/logo-svitco.webp'},
  notifications:{telegram:{enabled:false,recipient:''},email:{enabled:false,recipient:''},sms:{enabled:false,recipient:''},whatsapp:{enabled:false,recipient:''}},
 },
 services:[
  {id:'service-full',titleUk:'Ремонт квартир під ключ',titleEn:'Complete Apartment Renovation',descriptionUk:'Комплексне оновлення квартири з узгодженим переліком внутрішніх робіт.',descriptionEn:'A complete apartment renovation with an agreed scope of interior work.',image:'/assets/photos/service-full.webp',order:10,published:true,featured:true,portfolioCategory:'apartments'},
  {id:'service-shower',titleUk:'Ремонт та облаштування душових кімнат',titleEn:'Shower Room Renovation',descriptionUk:'Оздоблення, гідроізоляція та облаштування душової кімнати відповідно до погодженого проєкту.',descriptionEn:'Finishing, waterproofing and shower-room fit-out according to the agreed project.',image:'/assets/photos/bathroom-renovation.webp',order:20,published:true,featured:false,portfolioCategory:'showers'},
  {id:'service-toilet',titleUk:'Ремонт туалетів',titleEn:'Toilet Renovation',descriptionUk:'Оновлення окремих туалетних кімнат із підготовкою поверхонь та внутрішнім оздобленням.',descriptionEn:'Renovation of separate toilet rooms with surface preparation and interior finishing.',image:'/assets/photos/service-finishing.webp',order:30,published:true,featured:false,portfolioCategory:'toilets'},
  {id:'service-kitchen',titleUk:'Ремонт кухонь',titleEn:'Kitchen Renovation',descriptionUk:'Оновлення кухонного простору та внутрішнє оздоблення.',descriptionEn:'Kitchen-space renovation and interior finishing.',image:'/assets/photos/kitchen-renovation.webp',order:40,published:true,featured:false,portfolioCategory:'kitchens'},
  {id:'service-paint',titleUk:'Фарбування та оздоблення',titleEn:'Painting & Finishing',descriptionUk:'Підготовка поверхонь, фарбування та завершальне оздоблення.',descriptionEn:'Surface preparation, painting and finishing work.',image:'/assets/photos/service-painting.webp',order:50,published:true,featured:false,portfolioCategory:'painting'},
  {id:'service-floor',titleUk:'Підлога',titleEn:'Flooring',descriptionUk:'Підготовка та монтаж підлогових покриттів.',descriptionEn:'Preparation and installation of flooring.',image:'/assets/photos/service-flooring.webp',order:60,published:true,featured:false,portfolioCategory:'flooring'}
 ],
 team:[],projects:[],leads:[],media:[],notificationQueue:[],notificationAttempts:[],idempotency:[],
 content:{
  advantages:[{id:id(),titleUk:'Зрозуміла комунікація',titleEn:'Clear communication',textUk:'Узгоджуємо етапи та зміни.',textEn:'We align on stages and changes.',order:10,published:true},{id:id(),titleUk:'Акуратне виконання',titleEn:'Careful workmanship',textUk:'Дбайливо ставимося до простору.',textEn:'We treat the space with care.',order:20,published:true},{id:id(),titleUk:'Прозорий процес',titleEn:'Transparent process',textUk:'Ви знаєте, який етап виконується.',textEn:'You know which stage is underway.',order:30,published:true}],
  process:[{id:id(),titleUk:'Заявка',titleEn:'Enquiry',textUk:'Ви описуєте завдання та зручний канал зв’язку.',textEn:'You describe the job and preferred contact channel.',order:10,published:true},{id:id(),titleUk:'Обговорення',titleEn:'Discussion',textUk:'Уточнюємо обсяг робіт і деталі.',textEn:'We clarify the scope and details.',order:20,published:true},{id:id(),titleUk:'Погодження',titleEn:'Agreement',textUk:'Фіксуємо погоджені роботи перед стартом.',textEn:'We confirm the agreed work before starting.',order:30,published:true},{id:id(),titleUk:'Виконання',titleEn:'Work',textUk:'Виконуємо ремонт і підтримуємо зв’язок.',textEn:'We carry out the renovation and keep in touch.',order:40,published:true}],
  faq:[{id:id(),questionUk:'Як почати?',questionEn:'How do we start?',answerUk:'Залиште заявку та виберіть зручний спосіб зв’язку.',answerEn:'Send an enquiry and choose your preferred way to be contacted.',order:10,published:true}],
  cta:{titleUk:'Розкажіть про свій проєкт',titleEn:'Tell us about your project',textUk:'Залиште заявку, і ми зв’яжемося через обраний вами канал.',textEn:'Send an enquiry and we will contact you through your selected channel.'},
  footer:{textUk:'Ремонт квартир і внутрішнє оздоблення.',textEn:'Apartment renovation and interior finishing.'}
 },
 sections:[
  {id:'services',type:'services',titleUk:'Послуги з ремонту',titleEn:'Renovation Services',descriptionUk:'Оберіть потрібний напрям робіт.',descriptionEn:'Choose the type of work you need.',order:10,published:true,system:true},
  {id:'projects',type:'portfolio',titleUk:'Проєкти та портфоліо',titleEn:'Projects & Portfolio',descriptionUk:'Реальні роботи Svit&Co.',descriptionEn:'Real Svit&Co work.',order:20,published:true,system:true},
  {id:'process',type:'process',titleUk:'Як ми працюємо',titleEn:'How We Work',descriptionUk:'Зрозумілий процес від заявки до виконання.',descriptionEn:'A clear process from enquiry to completion.',order:30,published:true,system:true},
  {id:'team',type:'team',titleUk:'Наша команда',titleEn:'Our Team',descriptionUk:'Майстри, які працюють над вашими проєктами.',descriptionEn:'The people working on your projects.',order:40,published:true,system:true},
  {id:'advantages',type:'advantages',titleUk:'Наші принципи',titleEn:'Our Principles',descriptionUk:'Підхід до роботи та комунікації.',descriptionEn:'Our approach to work and communication.',order:50,published:true,system:true},
  {id:'faq',type:'faq',titleUk:'Поширені запитання',titleEn:'Frequently Asked Questions',descriptionUk:'Короткі відповіді перед першою розмовою.',descriptionEn:'Short answers before the first conversation.',order:60,published:true,system:true},
  {id:'contact',type:'cta',titleUk:'Розкажіть про свій проєкт',titleEn:'Tell us about your project',descriptionUk:'Залиште заявку на сайті.',descriptionEn:'Send an enquiry through the website.',order:70,published:true,system:true}
 ]
};

async function ensureStorage(){await fsp.mkdir(UPLOAD_DIR,{recursive:true});await fsp.mkdir(TMP_DIR,{recursive:true});try{await fsp.access(DB_PATH)}catch{await atomicWrite(structuredClone(defaults))}}
async function atomicWrite(data){writeQueue=writeQueue.then(async()=>{await fsp.mkdir(DATA_DIR,{recursive:true});const tmp=`${DB_PATH}.${process.pid}.tmp`;await fsp.writeFile(tmp,JSON.stringify(data,null,2),'utf8');await fsp.rename(tmp,DB_PATH)});return writeQueue}
async function backupDb(label='migration'){try{const stamp=new Date().toISOString().replace(/[:.]/g,'-');await fsp.copyFile(DB_PATH,path.join(DATA_DIR,`database.${label}.${stamp}.bak.json`))}catch{}}
function mergeMissing(target,source){for(const [k,v] of Object.entries(source)){if(target[k]===undefined)target[k]=structuredClone(v);else if(v&&typeof v==='object'&&!Array.isArray(v)&&target[k]&&typeof target[k]==='object'&&!Array.isArray(target[k]))mergeMissing(target[k],v)}return target}
async function migrate(db){let changed=false;const before=Number(db.schemaVersion||0);if(before<SCHEMA_VERSION)await backupDb('pre-v4');
 mergeMissing(db,defaults);
 if(!db.migrations.teamFromLegacy){const legacyName=clean(db.settings.ownerName||'',120);const legacyUk=clean(db.settings.aboutUk||'',1500);const legacyEn=clean(db.settings.aboutEn||'',1500);const legacyPhoto=clean(db.settings.aboutImage||'',500);if((legacyName&&legacyName!=='OWNER NAME')||legacyUk||legacyEn||legacyPhoto){db.team.push({id:id(),name:legacyName&&legacyName!=='OWNER NAME'?legacyName:'Svit&Co',roleUk:'Майстер',roleEn:'Craftsperson',descriptionUk:legacyUk,descriptionEn:legacyEn,photo:legacyPhoto||'',specializations:[],experience:'',order:10,published:true,legacyImported:true})}db.migrations.teamFromLegacy=now();changed=true}
 if(!db.migrations.servicePriorityV4){const serviceIds=new Set(db.services.map(x=>x.id));for(const s of defaults.services){if(!serviceIds.has(s.id)){db.services.push(structuredClone(s));changed=true}}db.migrations.servicePriorityV4=now();changed=true}
 db.services.sort((a,b)=>num(a.order)-num(b.order));
 for(const p of db.projects){if(p.published===undefined){p.published=true;changed=true}if(!p.category){p.category='apartments';changed=true}if(!Array.isArray(p.images)){p.images=[];changed=true}}
 db.schemaVersion=SCHEMA_VERSION;if(before!==SCHEMA_VERSION)changed=true;if(changed)await atomicWrite(db);return db}
async function readDb(){await ensureStorage();try{return await migrate(JSON.parse(await fsp.readFile(DB_PATH,'utf8')))}catch(err){console.error('DB read failed:',err.message);return structuredClone(defaults)}}
async function mutate(fn){const db=await readDb();const result=await fn(db);await atomicWrite(db);return result??db}
function requireAdmin(req,res,next){if(req.session?.admin===true)return next();res.status(401).json({error:'Unauthorized'})}

function detectType(buf){if(!buf||buf.length<12)return null;if(buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff)return'image/jpeg';if(buf.slice(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return'image/png';if(buf.slice(0,4).toString()==='RIFF'&&buf.slice(8,12).toString()==='WEBP')return'image/webp';const head=buf.slice(4,12).toString('ascii');if(head.includes('ftypavif'))return'image/avif';return null}
const tempStorage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,TMP_DIR),filename:(_r,_f,cb)=>cb(null,`${Date.now()}-${id()}.upload`)});
const upload=multer({storage:tempStorage,limits:{fileSize:8*1024*1024,files:12}});
async function finalizeFile(file,altUk='',altEn=''){const buf=await fsp.readFile(file.path);const type=detectType(buf);if(!type){await fsp.unlink(file.path).catch(()=>{});throw new Error('Invalid image file type.')}const ext={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','image/avif':'.avif'}[type];const filename=`${Date.now()}-${id()}${ext}`;const dest=path.join(UPLOAD_DIR,filename);await fsp.rename(file.path,dest);try{const q=type==='image/png'?'85':'82';await execFileAsync('convert',[dest,'-auto-orient','-resize','2560x2560>','-strip','-quality',q,dest],{timeout:20000})}catch{}const stat=await fsp.stat(dest);return{id:id(),url:`/uploads/${filename}`,mime:type,size:stat.size,altUk:clean(altUk,240),altEn:clean(altEn,240),createdAt:now()}}
async function safeUnlink(url){if(!String(url||'').startsWith('/uploads/'))return;const file=path.resolve(DATA_DIR,'.'+url);if(file.startsWith(UPLOAD_DIR))await fsp.unlink(file).catch(()=>{})}
function mediaUsage(db,url){const uses=[];if(db.settings.hero?.image===url)uses.push('Головний екран');if(db.settings.brand?.logoUrl===url)uses.push('Логотип');for(const s of db.services)if(s.image===url)uses.push(`Послуга: ${s.titleUk||s.titleEn}`);for(const t of db.team)if(t.photo===url)uses.push(`Команда: ${t.name}`);for(const p of db.projects){if(p.cover===url)uses.push(`Обкладинка: ${p.titleUk||p.titleEn}`);for(const im of p.images||[])if(im.url===url)uses.push(`Проєкт: ${p.titleUk||p.titleEn}`)}for(const s of db.sections)if(s.image===url)uses.push(`Секція: ${s.titleUk||s.titleEn}`);return uses}

app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],imgSrc:["'self'",'data:','blob:'],styleSrc:["'self'"],scriptSrc:["'self'"],connectSrc:["'self'"],fontSrc:["'self'",'data:'],objectSrc:["'none'"],frameAncestors:["'none'"],upgradeInsecureRequests:isProduction?[]:null}},crossOriginResourcePolicy:{policy:'same-origin'}}));
app.use(compression());app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true,limit:'2mb'}));
app.use(cookieSession({name:'svitco_admin',keys:[process.env.SESSION_SECRET||'local-development-secret-change-me'],maxAge:8*60*60*1000,httpOnly:true,secure:isProduction,sameSite:'lax'}));
app.use('/uploads',express.static(UPLOAD_DIR,{maxAge:isProduction?'7d':0}));app.use(express.static(path.join(ROOT,'public'),{extensions:['html'],maxAge:isProduction?'1h':0}));
const loginLimiter=rateLimit({windowMs:15*60*1000,limit:12});const leadLimiter=rateLimit({windowMs:15*60*1000,limit:8});
app.get('/api/health',(_q,r)=>r.json({ok:true,schema:SCHEMA_VERSION}));
app.get('/api/site',async(_q,r)=>{const db=await readDb();const safeSettings=structuredClone(db.settings);delete safeSettings.notifications;r.json({settings:safeSettings,services:db.services.filter(x=>x.published).sort((a,b)=>num(a.order)-num(b.order)),team:db.team.filter(x=>x.published).sort((a,b)=>num(a.order)-num(b.order)),projects:db.projects.filter(x=>x.published).sort((a,b)=>num(a.order)-num(b.order)),sections:db.sections.filter(x=>x.published).sort((a,b)=>num(a.order)-num(b.order)),content:db.content})});

function validateLead(body){const method=clean(body.preferredContact,20);const contact=clean(body.contact,180);if(!['phone','whatsapp','viber','telegram','email'].includes(method))return'Choose a valid contact method.';if(['phone','whatsapp','viber'].includes(method)&&!e164(contact))return'Use a phone number with international country code, for example +48…';if(method==='email'&&!validEmail(contact))return'Enter a valid email address.';if(method==='telegram'&&!(/^@[A-Za-z0-9_]{5,32}$/.test(contact)||/^https:\/\/t\.me\/[A-Za-z0-9_]{5,32}\/?$/.test(contact)))return'Enter a Telegram @username or https://t.me/… link.';return''}
function leadSummary(lead){return `Нова заявка Svit&Co\nІм’я: ${lead.name}\nПослуга: ${lead.service||'—'}\nБажаний канал: ${lead.preferredContact}\nКонтакт: ${lead.contact}\nПовідомлення: ${(lead.message||'—').slice(0,500)}\nЧас: ${lead.createdAt}\nАдмінка: ${baseUrl}/admin#lead-${lead.id}`}
function channelConfigured(ch){if(process.env.NOTIFICATION_TEST_MODE==='1')return true;if(ch==='telegram')return Boolean(process.env.TELEGRAM_BOT_TOKEN);if(ch==='email')return Boolean(process.env.RESEND_API_KEY&&process.env.RESEND_FROM_EMAIL);if(ch==='sms')return Boolean(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM_NUMBER);if(ch==='whatsapp')return Boolean(process.env.WHATSAPP_ACCESS_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID&&process.env.WHATSAPP_TEMPLATE_NAME);return false}
function channelPublicStatus(db,ch){const c=db.settings.notifications[ch]||{};return{enabled:Boolean(c.enabled),recipient:c.recipient||'',configured:channelConfigured(ch),status:channelConfigured(ch)?'configured':'not_configured'}}
function enqueueForLead(db,lead,onlyChannel=null){for(const ch of ['telegram','email','sms','whatsapp']){if(onlyChannel&&ch!==onlyChannel)continue;const cfg=db.settings.notifications[ch];if(!cfg?.enabled||!cfg.recipient)continue;db.notificationQueue.push({id:id(),leadId:lead.id,channel:ch,recipient:cfg.recipient,status:'pending',attempts:0,maxAttempts:4,nextAttemptAt:now(),createdAt:now(),lastError:'',providerId:''})}}
app.post('/api/leads',leadLimiter,upload.array('photos',5),async(req,res)=>{try{const b=req.body||{};if(b.website)return res.status(202).json({ok:true});const name=clean(b.name,120),method=clean(b.preferredContact,20),contact=clean(b.contact,180);if(!name)return res.status(400).json({error:'Name is required.'});const err=validateLead({preferredContact:method,contact});if(err)return res.status(400).json({error:err});const key=clean(req.get('Idempotency-Key')||b.idempotencyKey,100);const files=[];for(const f of req.files||[])files.push(await finalizeFile(f));let responseLead;await mutate(db=>{if(key){const prior=db.idempotency.find(x=>x.key===key&&Date.now()-new Date(x.createdAt).getTime()<24*3600e3);if(prior){responseLead=db.leads.find(x=>x.id===prior.leadId);return}}const lead={id:id(),createdAt:now(),updatedAt:now(),status:'new',locale:b.locale==='en'?'en':'uk',name,service:clean(b.service,160),preferredContact:method,contact,message:clean(b.message,4000),photos:files.map(x=>x.url),convenientTime:method==='phone'?clean(b.convenientTime,160):'',propertyType:clean(b.propertyType,100),area:clean(b.area,50),location:clean(b.location,160),startDate:clean(b.startDate,100),deliveryStatus:'queued'};db.leads.unshift(lead);for(const m of files)db.media.push(m);if(key)db.idempotency.push({key,leadId:lead.id,createdAt:now()});enqueueForLead(db,lead);responseLead=lead});kickWorker();res.status(201).json({ok:true,id:responseLead.id,message:responseLead.locale==='en'?'Thank you. Your enquiry has been saved.':'Дякуємо. Вашу заявку збережено.'})}catch(e){for(const f of req.files||[])await fsp.unlink(f.path).catch(()=>{});res.status(400).json({error:e.message||'Could not save enquiry.'})}});

app.post('/api/admin/login',loginLimiter,(req,res)=>{const configured=process.env.ADMIN_PASSWORD||'change-me-now';if(!safeEquals(req.body?.password||'',configured))return res.status(401).json({error:'Incorrect password.'});req.session.admin=true;res.json({ok:true,usingDefaultPassword:!process.env.ADMIN_PASSWORD})});
app.post('/api/admin/logout',requireAdmin,(req,res)=>{req.session=null;res.json({ok:true})});app.get('/api/admin/session',(req,res)=>res.json({authenticated:req.session?.admin===true}));
app.get('/api/admin/data',requireAdmin,async(_q,res)=>{const db=await readDb();const out=structuredClone(db);for(const ch of ['telegram','email','sms','whatsapp'])out.settings.notifications[ch].connection=channelPublicStatus(db,ch);res.json(out)});
app.patch('/api/admin/settings/:group',requireAdmin,async(req,res)=>{const group=req.params.group;const allowed=['hero','contacts','brand','seo','notifications','content'];if(!allowed.includes(group))return res.status(404).json({error:'Unknown settings group'});await mutate(db=>{if(group==='contacts'){for(const k of ['phone','email','whatsapp','viber','telegram','workingHours','serviceArea','country'])if(k in req.body)db.settings[k]=clean(req.body[k],500);if(Array.isArray(req.body.allowedContactMethods)&&req.body.allowedContactMethods.length)db.settings.allowedContactMethods=req.body.allowedContactMethods.filter(x=>['phone','whatsapp','viber','telegram','email'].includes(x));if(req.body.directButtons)db.settings.directButtons={...db.settings.directButtons,...req.body.directButtons}}else if(group==='notifications'){for(const ch of ['telegram','email','sms','whatsapp'])if(req.body[ch])db.settings.notifications[ch]={enabled:bool(req.body[ch].enabled),recipient:clean(req.body[ch].recipient,200)}}else if(group==='content'){db.content=mergeMissing({...db.content,...req.body},defaults.content)}else db.settings[group]={...db.settings[group],...req.body}});res.json({ok:true})});

async function crudCollection(req,res,name,normalize){const result=await mutate(db=>{const list=db[name];if(req.method==='POST'){const row=normalize(req.body,{id:id(),createdAt:now()});list.push(row);return row}const row=list.find(x=>x.id===req.params.id);if(!row){res.status(404);return{error:'Not found'}};if(req.method==='PATCH'){Object.assign(row,normalize(req.body,row),{updatedAt:now()});return row}if(req.method==='DELETE'){const i=list.indexOf(row);list.splice(i,1);return row}});if(res.statusCode===404)return res.json(result);res.json({ok:true,item:result})}
const normalizeService=(b,old)=>({...old,titleUk:clean(b.titleUk??old.titleUk,160),titleEn:clean(b.titleEn??old.titleEn,160),descriptionUk:clean(b.descriptionUk??old.descriptionUk,1600),descriptionEn:clean(b.descriptionEn??old.descriptionEn,1600),image:clean(b.image??old.image,500),order:num(b.order??old.order,10),published:b.published===undefined?old.published:bool(b.published),featured:b.featured===undefined?old.featured:bool(b.featured),portfolioCategory:clean(b.portfolioCategory??old.portfolioCategory,80)});
const normalizeTeam=(b,old)=>({...old,name:clean(b.name??old.name,160),roleUk:clean(b.roleUk??old.roleUk,180),roleEn:clean(b.roleEn??old.roleEn,180),descriptionUk:clean(b.descriptionUk??old.descriptionUk,1800),descriptionEn:clean(b.descriptionEn??old.descriptionEn,1800),photo:clean(b.photo??old.photo,500),experience:clean(b.experience??old.experience,120),specializations:Array.isArray(b.specializations)?b.specializations.map(x=>clean(x,120)).filter(Boolean):old.specializations||[],order:num(b.order??old.order,10),published:b.published===undefined?old.published:bool(b.published)});
const normalizeSection=(b,old)=>({...old,type:['text','text-image','gallery','advantages','faq','cta','services','portfolio','process','team'].includes(b.type)?b.type:old.type||'text',titleUk:clean(b.titleUk??old.titleUk,180),titleEn:clean(b.titleEn??old.titleEn,180),descriptionUk:clean(b.descriptionUk??old.descriptionUk,2400),descriptionEn:clean(b.descriptionEn??old.descriptionEn,2400),image:clean(b.image??old.image,500),order:num(b.order??old.order,10),published:b.published===undefined?old.published:bool(b.published),system:Boolean(old.system)});
for(const [route,name,norm] of [['services','services',normalizeService],['team','team',normalizeTeam],['sections','sections',normalizeSection]]){app.post(`/api/admin/${route}`,requireAdmin,(q,r)=>crudCollection(q,r,name,norm));app.patch(`/api/admin/${route}/:id`,requireAdmin,(q,r)=>crudCollection(q,r,name,norm));app.delete(`/api/admin/${route}/:id`,requireAdmin,async(req,res)=>{if(name==='sections'){const db=await readDb();const row=db.sections.find(x=>x.id===req.params.id);if(row?.system)return res.status(400).json({error:'System sections can be hidden but not deleted.'})}return crudCollection(req,res,name,norm)})}

app.post('/api/admin/media',requireAdmin,upload.array('images',10),async(req,res)=>{try{const created=[];for(const f of req.files||[])created.push(await finalizeFile(f,req.body.altUk,req.body.altEn));await mutate(db=>db.media.push(...created));res.status(201).json({ok:true,items:created})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/admin/media/:id',requireAdmin,async(req,res)=>{const item=await mutate(db=>{const m=db.media.find(x=>x.id===req.params.id);if(!m)return null;m.altUk=clean(req.body.altUk??m.altUk,240);m.altEn=clean(req.body.altEn??m.altEn,240);return m});if(!item)return res.status(404).json({error:'Not found'});res.json({ok:true,item})});
app.get('/api/admin/media/:id/usage',requireAdmin,async(req,res)=>{const db=await readDb(),m=db.media.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({error:'Not found'});res.json({usage:mediaUsage(db,m.url)})});
app.delete('/api/admin/media/:id',requireAdmin,async(req,res)=>{const db=await readDb(),m=db.media.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({error:'Not found'});const usage=mediaUsage(db,m.url);if(usage.length&&!req.body?.replacementUrl)return res.status(409).json({error:'Image is in use.',usage});const replacement=clean(req.body?.replacementUrl,500);if(replacement){const replace=o=>{for(const k of Object.keys(o||{}))if(o[k]===m.url)o[k]=replacement};replace(db.settings.hero);replace(db.settings.brand);db.services.forEach(replace);db.team.forEach(replace);db.sections.forEach(replace);for(const p of db.projects){replace(p);for(const im of p.images||[])replace(im)}}db.media=db.media.filter(x=>x.id!==m.id);await atomicWrite(db);await safeUnlink(m.url);res.json({ok:true})});

app.post('/api/admin/projects',requireAdmin,upload.array('images',10),async(req,res)=>{try{const images=[];for(const f of req.files||[])images.push(await finalizeFile(f,req.body.altUk,req.body.altEn));const project={id:id(),titleUk:clean(req.body.titleUk,160),titleEn:clean(req.body.titleEn,160),descriptionUk:clean(req.body.descriptionUk,2400),descriptionEn:clean(req.body.descriptionEn,2400),category:clean(req.body.category,80)||'apartments',location:clean(req.body.location,160),images,cover:images[0]?.url||'',published:bool(req.body.published),order:num(req.body.order,10),createdAt:now()};await mutate(db=>{db.projects.push(project);db.media.push(...images)});res.status(201).json({ok:true,item:project})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/admin/projects/:id',requireAdmin,async(req,res)=>{const project=await mutate(db=>{const p=db.projects.find(x=>x.id===req.params.id);if(!p)return null;for(const k of ['titleUk','titleEn','descriptionUk','descriptionEn','category','location','cover'])if(k in req.body)p[k]=clean(req.body[k],k.startsWith('description')?2400:500);if('published'in req.body)p.published=bool(req.body.published);if('order'in req.body)p.order=num(req.body.order);if(Array.isArray(req.body.imageOrder)){const map=new Map(p.images.map(x=>[x.id,x]));p.images=req.body.imageOrder.map(x=>map.get(x)).filter(Boolean)}return p});if(!project)return res.status(404).json({error:'Not found'});res.json({ok:true,item:project})});
app.post('/api/admin/projects/:id/images',requireAdmin,upload.array('images',10),async(req,res)=>{try{const images=[];for(const f of req.files||[])images.push(await finalizeFile(f,req.body.altUk,req.body.altEn));let found=false;await mutate(db=>{const p=db.projects.find(x=>x.id===req.params.id);if(!p)return;found=true;p.images.push(...images);if(!p.cover&&images[0])p.cover=images[0].url;db.media.push(...images)});if(!found)return res.status(404).json({error:'Not found'});res.status(201).json({ok:true,items:images})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/admin/projects/:id/images/:imageId',requireAdmin,async(req,res)=>{let removed=null;await mutate(db=>{const p=db.projects.find(x=>x.id===req.params.id);if(!p)return;const im=p.images.find(x=>x.id===req.params.imageId);if(!im)return;removed=im;p.images=p.images.filter(x=>x.id!==im.id);if(p.cover===im.url)p.cover=p.images[0]?.url||'';db.media=db.media.filter(x=>x.url!==im.url)});if(!removed)return res.status(404).json({error:'Not found'});await safeUnlink(removed.url);res.json({ok:true})});
app.delete('/api/admin/projects/:id',requireAdmin,async(req,res)=>{let removed=null;await mutate(db=>{const p=db.projects.find(x=>x.id===req.params.id);if(!p)return;removed=p;db.projects=db.projects.filter(x=>x.id!==p.id)});if(!removed)return res.status(404).json({error:'Not found'});res.json({ok:true})});

app.patch('/api/admin/leads/:id',requireAdmin,async(req,res)=>{const item=await mutate(db=>{const l=db.leads.find(x=>x.id===req.params.id);if(!l)return null;if(['new','contacted','completed','archived'].includes(req.body.status))l.status=req.body.status;l.updatedAt=now();return l});if(!item)return res.status(404).json({error:'Not found'});res.json({ok:true,item})});
app.post('/api/admin/leads/:id/retry',requireAdmin,async(req,res)=>{await mutate(db=>{const lead=db.leads.find(x=>x.id===req.params.id);if(!lead)return;enqueueForLead(db,lead,clean(req.body.channel,20)||null)});kickWorker();res.json({ok:true})});
app.get('/api/admin/leads.csv',requireAdmin,async(_q,res)=>{const db=await readDb();const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`;const rows=[['date','name','service','preferredContact','contact','status','message'],...db.leads.map(l=>[l.createdAt,l.name,l.service,l.preferredContact,l.contact,l.status,l.message])];res.type('text/csv').send(rows.map(r=>r.map(esc).join(',')).join('\n'))});

async function sendChannel(channel,recipient,textMsg,jobId){if(process.env.NOTIFICATION_TEST_MODE==='1')return{accepted:true,delivered:true,providerId:`test-${jobId}`};if(channel==='telegram'){const r=await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:recipient,text:textMsg,disable_web_page_preview:true})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.description||`Telegram HTTP ${r.status}`);return{accepted:true,delivered:true,providerId:String(j.result?.message_id||'')}}if(channel==='email'){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.RESEND_API_KEY}`,'Idempotency-Key':jobId},body:JSON.stringify({from:process.env.RESEND_FROM_EMAIL,to:[recipient],subject:'Нова заявка Svit&Co',text:textMsg})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`Email HTTP ${r.status}`);return{accepted:true,delivered:false,providerId:j.id||''}}if(channel==='sms'){const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN;const form=new URLSearchParams({Body:textMsg.slice(0,1500),From:process.env.TWILIO_FROM_NUMBER,To:recipient});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','authorization':`Basic ${Buffer.from(`${sid}:${token}`).toString('base64')}`},body:form});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||`SMS HTTP ${r.status}`);return{accepted:true,delivered:['delivered'].includes(j.status),providerId:j.sid||''}}if(channel==='whatsapp'){const leadLines=textMsg.split('\n').slice(1);const summary=leadLines.join(' | ').slice(0,900);const payload={messaging_product:'whatsapp',to:recipient,type:'template',template:{name:process.env.WHATSAPP_TEMPLATE_NAME,language:{code:process.env.WHATSAPP_TEMPLATE_LANGUAGE||'uk'},components:[{type:'body',parameters:[{type:'text',text:summary}]}]}};const r=await fetch(`https://graph.facebook.com/${process.env.WHATSAPP_API_VERSION||'v23.0'}/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||`WhatsApp HTTP ${r.status}`);return{accepted:true,delivered:false,providerId:j.messages?.[0]?.id||''}}throw new Error('Unsupported channel')}
async function processQueue(){const db=await readDb();const due=db.notificationQueue.filter(j=>['pending','retry'].includes(j.status)&&new Date(j.nextAttemptAt)<=new Date()).slice(0,5);if(!due.length)return;for(const job of due){const lead=db.leads.find(x=>x.id===job.leadId);if(!lead){job.status='failed';job.lastError='Lead not found';continue}job.attempts++;job.lastAttemptAt=now();try{if(!channelConfigured(job.channel))throw new Error('Channel not configured');const result=await sendChannel(job.channel,job.recipient,leadSummary(lead),job.id);job.status=result.delivered?'delivered':'accepted';job.providerId=result.providerId||'';job.lastError='';db.notificationAttempts.unshift({id:id(),queueId:job.id,leadId:lead.id,channel:job.channel,at:now(),status:job.status,providerId:job.providerId,error:''})}catch(e){job.lastError=clean(e.message,800);job.status=job.attempts>=job.maxAttempts?'failed':'retry';job.nextAttemptAt=new Date(Date.now()+Math.min(60,5*Math.pow(2,job.attempts))*60*1000).toISOString();db.notificationAttempts.unshift({id:id(),queueId:job.id,leadId:lead.id,channel:job.channel,at:now(),status:job.status,providerId:'',error:job.lastError})}}await atomicWrite(db)}
function kickWorker(){setTimeout(()=>processQueue().catch(e=>console.error('Notification worker:',e.message)),100)}
app.post('/api/admin/notifications/test',requireAdmin,async(req,res)=>{const channel=clean(req.body.channel,20),db=await readDb(),cfg=db.settings.notifications[channel];if(!cfg?.recipient)return res.status(400).json({error:'Recipient is not configured.'});if(!channelConfigured(channel))return res.status(400).json({error:'Channel is not configured in environment variables.'});try{const result=await sendChannel(channel,cfg.recipient,'Тестове сповіщення Svit&Co. Підключення працює.',`test-${id()}`);res.json({ok:true,result})}catch(e){res.status(502).json({error:e.message})}});

app.get('/robots.txt',(_q,r)=>r.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ${baseUrl}/sitemap.xml\n`));app.get('/sitemap.xml',(_q,r)=>r.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${baseUrl}/uk</loc></url><url><loc>${baseUrl}/en</loc></url></urlset>`));app.get(['/uk','/en','/uk/privacy','/en/privacy','/uk/terms','/en/terms'],(_q,r)=>r.sendFile(path.join(ROOT,'public','index.html')));app.get('/admin',(_q,r)=>r.sendFile(path.join(ROOT,'public','admin.html')));
app.use((err,_q,res,_n)=>{console.error(err);res.status(400).json({error:err.message||'Request failed'})});
ensureStorage().then(async()=>{await readDb();workerTimer=setInterval(()=>processQueue().catch(e=>console.error(e.message)),60_000);workerTimer.unref?.();app.listen(PORT,()=>console.log(`Svit&Co listening on ${PORT}; data: ${DATA_DIR}`))}).catch(e=>{console.error(e);process.exit(1)});
